steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.pattern_miner', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_8'
